services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile  
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: ./docker/spring/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
